// SPDX-License-Identifier: AGPL-3.0-or-later
import { assertV4Document, defaultDocument, uuid, type Bounds, type Constraint, type ContinuousMediaSettingsV1, type DitherSettings, type FontResource, type LabelDocument, type LabelElement, type Resource , isEffectivelyLocked, isEffectivelyVisible } from './model.js';
export interface SdkBounds {x:number;y:number;width:number;height:number}
export interface SdkResource {id:string;mediaType:string;sha256:string;dataBase64:string}
export interface SdkDocument {version:4;name:string;media:{width:number;height:number;unit:'micrometre';dpi:number;orientation:'portrait'|'landscape';printableBounds:SdkBounds;shape:'rectangle'|'round';continuous:boolean;zones:{id:string;bounds:SdkBounds;cloneOf?:string|null}[]};coordinateSystem:{unit:'micrometre';origin:'top-left';rounding:'half-away-from-zero'};elements:Record<string,unknown>[];resources:SdkResource[];fields:{key:string;label:string}[];extensions:Record<string,unknown>}
interface EditorMetadata {id:string;createdAt:string;modifiedAt:string;template?:LabelDocument['template'];continuousSettings?:ContinuousMediaSettingsV1;fonts:LabelDocument['fonts'];resourceNames:Record<string,string>;elements:Record<string,{name:string;fontFamily?:string;fontWeight?:number;fit?:string;dither?:DitherSettings;invert?:boolean;constraints?:unknown}>}
const mm=(value:number)=>Math.sign(value)*Math.floor(Math.abs(value)*1000+.5);const fromMm=(value:number)=>value/1000;const bounds=(value:Bounds):SdkBounds=>({x:mm(value.x),y:mm(value.y),width:mm(value.width),height:mm(value.height)});const fromBounds=(value:SdkBounds):Bounds=>({x:fromMm(value.x),y:fromMm(value.y),width:fromMm(value.width),height:fromMm(value.height)});
const common=(element:LabelElement,document:LabelDocument)=>{const transform=element.type==='group'?{...element.transform,x:0,y:0,rotation:0}:element.transform;return{id:element.id,transform:{...bounds(transform),rotationMillidegrees:Math.round(transform.rotation*1000)},zOrder:element.zIndex,visible:isEffectivelyVisible(document,element),locked:isEffectivelyLocked(document,element),groupId:element.groupId??null,constraints:element.constraints||rendersContained(element)?{preserveAspect:rendersContained(element)||(element.constraints?.some(item=>item.kind==='aspect')??false),zone:String(element.constraints?.find(item=>item.kind==='zone')?.value??'')||null}:null}};
/** The canvas always letterboxes SVGs and contain-fit images, so the printer must keep the same ratio instead of stretching artwork to the element box. */
const rendersContained=(element:LabelElement):boolean=>element.type==='svg'||(element.type==='image'&&element.fit==='contain');
export function toSdkDocument(document:LabelDocument):SdkDocument {assertV4Document(document);const allResources=[...document.resources,...document.fonts.filter(font=>!document.resources.some(resource=>resource.id===font.id))];const metadata:EditorMetadata={id:document.id,createdAt:document.createdAt,modifiedAt:document.modifiedAt,template:document.template,continuousSettings:document.media.continuousSettings,fonts:document.fonts,resourceNames:Object.fromEntries(allResources.map(resource=>[resource.id,resource.name])),elements:Object.fromEntries(document.elements.map(element=>[element.id,{name:element.name,...(element.type==='text'?{fontFamily:element.fontFamily,fontWeight:element.fontWeight}:{}),...(element.type==='image'?{fit:element.fit,dither:element.dither,invert:element.invert}:{}),constraints:element.constraints}]))};const images=document.elements.filter(element=>element.type==='image');const preservedDither=document.extensions?.['makersbrain.render:dither'];const preferred=images.find(element=>element.dither?.algorithm==='floyd-steinberg')??images.find(element=>element.dither?.algorithm==='atkinson')??images.find(element=>element.dither?.algorithm==='bayer')??images.find(element=>element.dither);const thermalDither=mergeDither(preservedDither,preferred?.dither);const imageRendering=mergeImageRendering(document.extensions?.['makersbrain.render:images'],images);
  const elements=document.elements.map(element=>{const base=common(element,document);switch(element.type){case'text':return{...base,type:'text',text:element.text,fontResource:element.fontResourceId??document.fonts.find(font=>font.family===element.fontFamily&&font.weight===element.fontWeight)?.id??null,fontSize:mm(element.fontSize),horizontalAlign:element.horizontalAlign,verticalAlign:element.verticalAlign,overflow:element.overflow};case'image':return{...base,type:'image',resource:element.resourceId,crop:element.crop?bounds(element.crop):null};case'svg':return{...base,type:'svg',resource:element.resourceId};case'line':return{...base,type:'line',strokeWidth:mm(element.strokeWidth)};case'rectangle':case'ellipse':case'triangle':return{...base,type:element.type,strokeWidth:mm(element.strokeWidth),fill:element.filled};case'barcode':return{...base,type:'barcode',data:element.value,symbology:element.symbology==='upca'?'upc-a':element.symbology,humanReadable:element.showText};case'qr':return{...base,type:'qr-code',data:element.value,errorCorrection:element.errorCorrection};case'group':return{...base,type:'group',children:element.childIds}}});
  return{version:4,name:document.title,media:{width:mm(document.media.width),height:mm(document.media.height),unit:'micrometre',dpi:document.media.dpi,orientation:document.media.orientation,printableBounds:bounds(document.media.printableBounds),shape:document.media.shape==='round'?'round':'rectangle',continuous:document.media.shape==='continuous',zones:(document.media.zones??[]).map(zone=>({id:zone.id,bounds:bounds(zone),cloneOf:zone.cloneOf??null}))},coordinateSystem:{unit:'micrometre',origin:'top-left',rounding:'half-away-from-zero'},elements,resources:allResources.map(resource=>({id:resource.id,mediaType:resource.mimeType,sha256:resource.sha256,dataBase64:resource.data})),fields:(document.template?.fields??[]).map(key=>({key,label:document.template?.fieldLabels?.[key]??key})),extensions:{...(document.extensions??{}),'makersbrain.render:dither':thermalDither,...(Object.keys(imageRendering).length?{'makersbrain.render:images':imageRendering}:{}),'makersbrain.editor:state':metadata}};
}
const sdkCommon=(raw:Record<string,unknown>,metadata:EditorMetadata):Omit<LabelElement,'type'>=>{const transform=raw.transform as SdkBounds&{rotationMillidegrees?:number};const saved=metadata.elements[String(raw.id)]??{name:String(raw.type)};const constraints=saved.constraints??canonicalConstraints(raw.constraints);return{id:String(raw.id),name:saved.name,transform:{...fromBounds(transform),rotation:fromMm(transform.rotationMillidegrees??0)},zIndex:Number(raw.zOrder),visible:raw.visible!==false,locked:raw.locked===true,...(raw.groupId?{groupId:String(raw.groupId)}:{}),...(constraints?{constraints:constraints as never}:{})} as Omit<LabelElement,'type'>};
export function fromSdkDocument(value:unknown):LabelDocument {if(!value||typeof value!=='object')throw new Error('Document must be an object');const sdk=value as Partial<SdkDocument>;if(sdk.version!==4||!sdk.media||sdk.media.unit!=='micrometre'||!sdk.coordinateSystem||!Array.isArray(sdk.elements)||!Array.isArray(sdk.resources))throw new Error('Invalid canonical v4 document');const metadata=editorMetadata(sdk.extensions?.['makersbrain.editor:state']);const seed=defaultDocument();const complete:EditorMetadata={id:metadata.id??uuid(),createdAt:metadata.createdAt??new Date().toISOString(),modifiedAt:metadata.modifiedAt??new Date().toISOString(),template:metadata.template,continuousSettings:metadata.continuousSettings,fonts:metadata.fonts??[],resourceNames:metadata.resourceNames??{},elements:metadata.elements??{}};const resources:Resource[]=sdk.resources.map(resource=>({id:resource.id,name:complete.resourceNames[resource.id]??resource.id,mimeType:resource.mediaType,sha256:resource.sha256,data:resource.dataBase64}));const globalDither=ditherSetting(sdk.extensions?.['makersbrain.render:dither']);const imageRendering=renderImages(sdk.extensions?.['makersbrain.render:images']);
  const elements=sdk.elements.map(raw=>{const base=sdkCommon(raw,complete);const type=String(raw.type);if(type==='text')return{...base,type:'text',text:String(raw.text??''),fontFamily:complete.elements[String(raw.id)]?.fontFamily??'sans-serif',fontResourceId:typeof raw.fontResource==='string'?raw.fontResource:undefined,fontSize:fromMm(Number(raw.fontSize)),fontWeight:complete.elements[String(raw.id)]?.fontWeight??400,horizontalAlign:raw.horizontalAlign,verticalAlign:raw.verticalAlign,overflow:raw.overflow};if(type==='image'){const saved=complete.elements[String(raw.id)];return{...base,type:'image',resourceId:String(raw.resource),fit:saved?.fit??'contain',...(raw.crop?{crop:fromBounds(raw.crop as SdkBounds)}:{}),dither:saved?.dither??globalDither,invert:saved?.invert===true||imageInvert(imageRendering[String(raw.id)])}}if(type==='svg')return{...base,type:'svg',resourceId:String(raw.resource)};if(type==='barcode')return{...base,type:'barcode',value:String(raw.data??''),symbology:raw.symbology==='upc-a'?'upca':raw.symbology,showText:raw.humanReadable===true};if(type==='qr-code'||type==='qr')return{...base,type:'qr',value:String(raw.data??''),errorCorrection:raw.errorCorrection};if(type==='group')return{...base,type:'group',childIds:raw.children};return{...base,type,strokeWidth:fromMm(Number(raw.strokeWidth??0)),filled:raw.fill===true}}) as LabelElement[];
  const editorFonts=complete.fonts.map(font=>resources.find(resource=>resource.id===font.id)?font:{...font});const zones=sdk.media.zones?.map(zone=>({id:zone.id,name:zone.id,...fromBounds(zone.bounds),...(zone.cloneOf?{cloneOf:zone.cloneOf}:{})}));const interpreted=new Set(['makersbrain.editor:state',...(metadata.id&&metadata.elements?['makersbrain.render:dither','makersbrain.render:images']:[])]);const extensions=structuredClone(Object.fromEntries(Object.entries(sdk.extensions??{}).filter(([key])=>!interpreted.has(key))));const canonicalFields=sdk.fields??[];const canonicalLabels=Object.fromEntries(canonicalFields.map(field=>[field.key,field.label]));const template=complete.template?{...complete.template,fields:canonicalFields.length?canonicalFields.map(field=>field.key):complete.template.fields,fieldLabels:{...(complete.template.fieldLabels??{}),...canonicalLabels}}:canonicalFields.length?{fields:canonicalFields.map(field=>field.key),fieldLabels:canonicalLabels,records:[],currentRecord:0}:undefined;const document:LabelDocument={version:4,id:complete.id,title:sdk.name??'Untitled label',media:{width:fromMm(sdk.media.width),height:fromMm(sdk.media.height),unit:'mm',dpi:sdk.media.dpi,orientation:sdk.media.orientation,printableBounds:fromBounds(sdk.media.printableBounds),shape:sdk.media.continuous?'continuous':sdk.media.shape,...(zones?.length?{zones}:{}),...(complete.continuousSettings?{continuousSettings:complete.continuousSettings}:{})},coordinateSystem:seed.coordinateSystem,elements,resources:resources.filter(resource=>!editorFonts.some(font=>font.id===resource.id)),fonts:editorFonts,...(template?{template}:{}),...(Object.keys(extensions).length?{extensions}:{}),createdAt:complete.createdAt,modifiedAt:complete.modifiedAt};assertV4Document(document);return document;
}

function renderImages(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))return{};return value as Record<string,unknown>}
function imageInvert(value:unknown):boolean{return!!value&&typeof value==='object'&&!Array.isArray(value)&&(value as{invert?:unknown}).invert===true}
function mergeImageRendering(value:unknown,images:Extract<LabelElement,{type:'image'}>[]):Record<string,unknown>{const result=structuredClone(renderImages(value));for(const image of images){const saved=result[image.id];const entry=saved&&typeof saved==='object'&&!Array.isArray(saved)?{...(saved as Record<string,unknown>)}:{};if(image.invert)entry.invert=true;else delete entry.invert;if(Object.keys(entry).length)result[image.id]=entry;else delete result[image.id]}return result}
function mergeDither(preserved:unknown,selected:DitherSettings|undefined):unknown{if(isRecord(preserved))return{...structuredClone(preserved),...(selected??{})};return selected??preserved??{algorithm:'auto',threshold:128}}
function canonicalConstraints(value:unknown):LabelElement['constraints']|undefined{if(!isRecord(value))return undefined;const constraints:NonNullable<LabelElement['constraints']>=[];if(value.preserveAspect===true)constraints.push({kind:'aspect'});if(typeof value.zone==='string'&&value.zone)constraints.push({kind:'zone',value:value.zone});return constraints}
function ditherSetting(value:unknown):DitherSettings|undefined{if(!value||typeof value!=='object')return undefined;const setting=value as{algorithm?:unknown;threshold?:unknown};if(!['auto','threshold','bayer','floyd-steinberg','atkinson'].includes(String(setting.algorithm))||!Number.isInteger(setting.threshold)||Number(setting.threshold)<0||Number(setting.threshold)>255)return undefined;return{algorithm:setting.algorithm as DitherSettings['algorithm'],threshold:Number(setting.threshold)}}
function editorMetadata(value:unknown):Partial<EditorMetadata>{if(!value||typeof value!=='object'||Array.isArray(value))return{};const raw=value as Partial<EditorMetadata>;const continuousSettings=continuousMediaSettings(raw.continuousSettings);return{...(typeof raw.id==='string'?{id:raw.id}:{}),...(typeof raw.createdAt==='string'?{createdAt:raw.createdAt}:{}),...(typeof raw.modifiedAt==='string'?{modifiedAt:raw.modifiedAt}:{}),...(isTemplate(raw.template)?{template:structuredClone(raw.template)}:{}),...(continuousSettings?{continuousSettings}:{}),...(Array.isArray(raw.fonts)?{fonts:fontResources(raw.fonts)}:{}),...(isRecord(raw.resourceNames)?{resourceNames:stringRecord(raw.resourceNames)}:{}),...(isRecord(raw.elements)?{elements:elementMetadata(raw.elements)}:{})}}
function isRecord(value:unknown):value is Record<string,unknown>{return!!value&&typeof value==='object'&&!Array.isArray(value)}
function isTemplate(value:unknown):value is LabelDocument['template']{if(!isRecord(value)||!Array.isArray(value.fields)||!value.fields.every(field=>typeof field==='string')||!Array.isArray(value.records)||!Number.isSafeInteger(value.currentRecord))return false;if(value.fieldLabels!==undefined&&(!isRecord(value.fieldLabels)||!Object.values(value.fieldLabels).every(label=>typeof label==='string')))return false;return value.records.every(record=>isRecord(record)&&Object.values(record).every(field=>typeof field==='string'))}
function continuousMediaSettings(value:unknown):ContinuousMediaSettingsV1|undefined{if(!isRecord(value)||value.version!==1||!['fixed','fit-content'].includes(String(value.lengthMode))||!['per-record','uniform-longest'].includes(String(value.batchLengthMode)))return undefined;const numbers=['fixedLengthMm','leadingMarginMm','trailingMarginMm'] as const;if(!numbers.every(key=>Number.isFinite(value[key])&&Number(value[key])>=0))return undefined;for(const key of ['preferredMinimumLengthMm','preferredMaximumLengthMm'] as const)if(value[key]!==undefined&&(!Number.isFinite(value[key])||Number(value[key])<=0))return undefined;return{version:1,lengthMode:value.lengthMode as ContinuousMediaSettingsV1['lengthMode'],fixedLengthMm:Number(value.fixedLengthMm),leadingMarginMm:Number(value.leadingMarginMm),trailingMarginMm:Number(value.trailingMarginMm),...(value.preferredMinimumLengthMm===undefined?{}:{preferredMinimumLengthMm:Number(value.preferredMinimumLengthMm)}),...(value.preferredMaximumLengthMm===undefined?{}:{preferredMaximumLengthMm:Number(value.preferredMaximumLengthMm)}),batchLengthMode:value.batchLengthMode as ContinuousMediaSettingsV1['batchLengthMode']}}
function stringRecord(value:unknown):Record<string,string>{if(!isRecord(value))return{};return Object.fromEntries(Object.entries(value).filter((entry):entry is[string,string]=>typeof entry[1]==='string'))}
function fontResources(value:unknown):FontResource[]{if(!Array.isArray(value))return[];return value.filter((font):font is FontResource=>isRecord(font)&&typeof font.id==='string'&&typeof font.name==='string'&&typeof font.mimeType==='string'&&typeof font.sha256==='string'&&typeof font.data==='string'&&typeof font.family==='string'&&Number.isFinite(font.weight)&&(font.style==='normal'||font.style==='italic'))}
function elementMetadata(value:unknown):EditorMetadata['elements']{if(!isRecord(value))return{};const result:EditorMetadata['elements']={};for(const[id,item]of Object.entries(value)){if(!isRecord(item))continue;const dither=ditherSetting(item.dither);const constraints=editorConstraints(item.constraints);result[id]={name:typeof item.name==='string'?item.name:id,...(typeof item.fontFamily==='string'?{fontFamily:item.fontFamily}:{}),...(Number.isFinite(item.fontWeight)?{fontWeight:Number(item.fontWeight)}:{}),...(['contain','cover','stretch'].includes(String(item.fit))?{fit:String(item.fit)}:{}),...(dither?{dither}:{}),...(typeof item.invert==='boolean'?{invert:item.invert}:{}),...(constraints?{constraints}:{})}}return result}
function editorConstraints(value:unknown):Constraint[]|undefined{if(!Array.isArray(value))return undefined;const result:Constraint[]=[];for(const item of value){if(!isRecord(item)||!['inside-media','aspect','min-size','zone'].includes(String(item.kind)))continue;result.push({kind:item.kind as Constraint['kind'],...(typeof item.value==='number'||typeof item.value==='string'?{value:item.value}:{})})}return result}
