// SPDX-License-Identifier: AGPL-3.0-or-later
import { assertV4Document, defaultDocument, uuid, type Bounds, type LabelDocument, type LabelElement, type Resource } from './model.js';
export interface SdkBounds {x:number;y:number;width:number;height:number}
export interface SdkResource {id:string;mediaType:string;sha256:string;dataBase64:string}
export interface SdkDocument {version:4;name:string;media:{width:number;height:number;unit:'micrometre';dpi:number;orientation:'portrait'|'landscape';printableBounds:SdkBounds;shape:'rectangle'|'round';continuous:boolean;zones:{id:string;bounds:SdkBounds;cloneOf?:string|null}[]};coordinateSystem:{unit:'micrometre';origin:'top-left';rounding:'half-away-from-zero'};elements:Record<string,unknown>[];resources:SdkResource[];fields:{key:string;label:string}[];extensions:Record<string,unknown>}
interface EditorMetadata {id:string;createdAt:string;modifiedAt:string;template?:LabelDocument['template'];fonts:LabelDocument['fonts'];resourceNames:Record<string,string>;elements:Record<string,{name:string;fontFamily?:string;fontWeight?:number;fit?:string;dither?:unknown;constraints?:unknown}>}
const mm=(value:number)=>Math.sign(value)*Math.floor(Math.abs(value)*1000+.5);const fromMm=(value:number)=>value/1000;const bounds=(value:Bounds):SdkBounds=>({x:mm(value.x),y:mm(value.y),width:mm(value.width),height:mm(value.height)});const fromBounds=(value:SdkBounds):Bounds=>({x:fromMm(value.x),y:fromMm(value.y),width:fromMm(value.width),height:fromMm(value.height)});
const common=(element:LabelElement)=>({id:element.id,transform:{...bounds(element.transform),rotationMillidegrees:Math.round(element.transform.rotation*1000)},zOrder:element.zIndex,visible:element.visible,locked:element.locked,groupId:element.groupId??null,constraints:element.constraints?{preserveAspect:element.constraints.some(item=>item.kind==='aspect'),zone:null}:null});
export function toSdkDocument(document:LabelDocument):SdkDocument {assertV4Document(document);const allResources=[...document.resources,...document.fonts.filter(font=>!document.resources.some(resource=>resource.id===font.id))];const metadata:EditorMetadata={id:document.id,createdAt:document.createdAt,modifiedAt:document.modifiedAt,template:document.template,fonts:document.fonts,resourceNames:Object.fromEntries(allResources.map(resource=>[resource.id,resource.name])),elements:Object.fromEntries(document.elements.map(element=>[element.id,{name:element.name,...(element.type==='text'?{fontFamily:element.fontFamily,fontWeight:element.fontWeight}:{}),...(element.type==='image'?{fit:element.fit,dither:element.dither}:{}),constraints:element.constraints}]))};
  const elements=document.elements.map(element=>{const base=common(element);switch(element.type){case'text':return{...base,type:'text',text:element.text,fontResource:document.fonts.find(font=>font.family===element.fontFamily&&font.weight===element.fontWeight)?.id??null,fontSize:mm(element.fontSize),horizontalAlign:element.horizontalAlign,verticalAlign:element.verticalAlign,overflow:element.overflow};case'image':return{...base,type:'image',resource:element.resourceId,crop:element.crop?bounds(element.crop):null};case'svg':return{...base,type:'svg',resource:element.resourceId};case'line':return{...base,type:'line',strokeWidth:mm(element.strokeWidth)};case'rectangle':case'ellipse':case'triangle':return{...base,type:element.type,strokeWidth:mm(element.strokeWidth),fill:element.filled};case'barcode':return{...base,type:'barcode',data:element.value,symbology:element.symbology==='upca'?'upc-a':element.symbology,humanReadable:element.showText};case'qr':return{...base,type:'qr-code',data:element.value,errorCorrection:element.errorCorrection};case'group':return{...base,type:'group',children:element.childIds}}});
  return{version:4,name:document.title,media:{width:mm(document.media.width),height:mm(document.media.height),unit:'micrometre',dpi:document.media.dpi,orientation:document.media.orientation,printableBounds:bounds(document.media.printableBounds),shape:document.media.shape==='round'?'round':'rectangle',continuous:document.media.shape==='continuous',zones:(document.media.zones??[]).map(zone=>({id:zone.id,bounds:bounds(zone),cloneOf:zone.cloneOf??null}))},coordinateSystem:{unit:'micrometre',origin:'top-left',rounding:'half-away-from-zero'},elements,resources:allResources.map(resource=>({id:resource.id,mediaType:resource.mimeType,sha256:resource.sha256,dataBase64:resource.data})),fields:(document.template?.fields??[]).map(key=>({key,label:key})),extensions:{...(document.extensions??{}),'makersbrain.editor:state':metadata}};
}
const sdkCommon=(raw:Record<string,unknown>,metadata:EditorMetadata):Omit<LabelElement,'type'>=>{const transform=raw.transform as SdkBounds&{rotationMillidegrees?:number};const saved=metadata.elements[String(raw.id)]??{name:String(raw.type)};return{id:String(raw.id),name:saved.name,transform:{...fromBounds(transform),rotation:fromMm(transform.rotationMillidegrees??0)},zIndex:Number(raw.zOrder),visible:raw.visible!==false,locked:raw.locked===true,...(raw.groupId?{groupId:String(raw.groupId)}:{}),...(saved.constraints?{constraints:saved.constraints as never}:{})} as Omit<LabelElement,'type'>};
export function fromSdkDocument(value:unknown):LabelDocument {if(!value||typeof value!=='object')throw new Error('Document must be an object');const sdk=value as Partial<SdkDocument>;if(sdk.version!==4||!sdk.media||sdk.media.unit!=='micrometre'||!sdk.coordinateSystem||!Array.isArray(sdk.elements)||!Array.isArray(sdk.resources))throw new Error('Invalid canonical v4 document');const metadata=(sdk.extensions?.['makersbrain.editor:state']??{}) as Partial<EditorMetadata>;const seed=defaultDocument();const complete:EditorMetadata={id:metadata.id??uuid(),createdAt:metadata.createdAt??new Date().toISOString(),modifiedAt:metadata.modifiedAt??new Date().toISOString(),template:metadata.template,fonts:metadata.fonts??[],resourceNames:metadata.resourceNames??{},elements:metadata.elements??{}};const resources:Resource[]=sdk.resources.map(resource=>({id:resource.id,name:complete.resourceNames[resource.id]??resource.id,mimeType:resource.mediaType,sha256:resource.sha256,data:resource.dataBase64}));
  const elements=sdk.elements.map(raw=>{const base=sdkCommon(raw,complete);const type=String(raw.type);if(type==='text')return{...base,type:'text',text:String(raw.text??''),fontFamily:complete.elements[String(raw.id)]?.fontFamily??'sans-serif',fontSize:fromMm(Number(raw.fontSize)),fontWeight:complete.elements[String(raw.id)]?.fontWeight??400,horizontalAlign:raw.horizontalAlign,verticalAlign:raw.verticalAlign,overflow:raw.overflow};if(type==='image')return{...base,type:'image',resourceId:String(raw.resource),fit:complete.elements[String(raw.id)]?.fit??'contain',...(raw.crop?{crop:fromBounds(raw.crop as SdkBounds)}:{}),dither:complete.elements[String(raw.id)]?.dither};if(type==='svg')return{...base,type:'svg',resourceId:String(raw.resource)};if(type==='barcode')return{...base,type:'barcode',value:String(raw.data??''),symbology:raw.symbology==='upc-a'?'upca':raw.symbology,showText:raw.humanReadable===true};if(type==='qr-code'||type==='qr')return{...base,type:'qr',value:String(raw.data??''),errorCorrection:raw.errorCorrection};if(type==='group')return{...base,type:'group',childIds:raw.children};return{...base,type,strokeWidth:fromMm(Number(raw.strokeWidth??0)),filled:raw.fill===true}}) as LabelElement[];
  const editorFonts=complete.fonts.map(font=>resources.find(resource=>resource.id===font.id)?font:{...font});const zones=sdk.media.zones?.map(zone=>({id:zone.id,name:zone.id,...fromBounds(zone.bounds),...(zone.cloneOf?{cloneOf:zone.cloneOf}:{})}));const extensions=Object.fromEntries(Object.entries(sdk.extensions??{}).filter(([key])=>key!=='makersbrain.editor:state'));const document:LabelDocument={version:4,id:complete.id,title:sdk.name??'Untitled label',media:{width:fromMm(sdk.media.width),height:fromMm(sdk.media.height),unit:'mm',dpi:sdk.media.dpi,orientation:sdk.media.orientation,printableBounds:fromBounds(sdk.media.printableBounds),shape:sdk.media.continuous?'continuous':sdk.media.shape,...(zones?.length?{zones}:{})},coordinateSystem:seed.coordinateSystem,elements,resources:resources.filter(resource=>!editorFonts.some(font=>font.id===resource.id)),fonts:editorFonts,...(complete.template?{template:complete.template}:{}),...(Object.keys(extensions).length?{extensions}:{}),createdAt:complete.createdAt,modifiedAt:complete.modifiedAt};assertV4Document(document);return document;
}
