import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
test.use({ deviceScaleFactor: 3, viewport: { width: 1280, height: 800 } });
test('bundled font embeds and prints', async ({ page }) => {
  const fixture = await readFile(new URL('../../packages/label-editor/tests/fixtures/sdk-v4-text.mb-label.json', import.meta.url));
  const problems: string[] = [];
  page.on('pageerror', (e) => problems.push(String(e)));
  await page.goto('/');
  await page.locator('input[type=file][accept*="mb-label"]').setInputFiles({ name: 'f.mb-label.json', mimeType: 'application/json', buffer: fixture });
  await expect(page.locator('footer')).toContainText('Opened SDK compatibility');
  await page.getByText('Assets', { exact: true }).first().click();
  const row = page.locator('.bundled-font');
  console.log('BUNDLED:', await row.allTextContents());
  await row.filter({ hasText: 'IBM Plex Sans Bold' }).click();
  await page.waitForTimeout(1500);
  console.log('FETCH:', await page.evaluate(async () => { const links = performance.getEntriesByType('resource').map((e) => e.name).filter((n) => n.includes('.ttf')); const probe = links[0] ? await fetch(links[0]).then((r) => r.status + ' ' + (r.ok ? 'ok' : 'denied')).catch((e) => String(e)) : 'no ttf request'; return JSON.stringify({ links, probe }); }));
  console.log('STATUS:', await page.locator('.assets').innerText().then((t) => t.split('\n').filter((l) => l.includes('Added') || l.includes('unavailable') || l.includes('mismatch')).join(' | ')));
  await page.getByText('Layers', { exact: true }).first().click();
  await page.locator('.element.text[data-id="text-1"]').click({ force: true });
  const select = page.getByRole('combobox', { name: 'Font' });
  console.log('OPTIONS:', await select.locator('option').allTextContents());
  await select.selectOption({ index: 1 });
  await page.getByText('File', { exact: true }).click();
  const download = page.waitForEvent('download', { timeout: 10000 }).catch(() => undefined);
  await page.getByRole('button', { name: 'Export PNG' }).click();
  await page.waitForTimeout(1500);
  console.log('FOOTER:', await page.locator('footer').first().innerText());
  console.log('DOWNLOAD:', (await download)?.suggestedFilename() ?? 'none');
  await page.getByText('Edit', { exact: true }).click().catch(() => {});
  await page.keyboard.press('Escape');
  await page.locator('.media').first().screenshot({ path: '/tmp/claude-1000/-home-rick-projects-caddy-makersbrain-mb-label-editor/dc1b9e19-67e5-4619-ac38-2ea6811c2698/scratchpad/bundled-render.png' });
  console.log('PAGE ERRORS:', problems.join(' | '));
});
