import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
test('a woff2 face exports through the SDK', async ({ page }) => {
  const fixture = await readFile(new URL('../../packages/label-editor/tests/fixtures/sdk-v4-text.mb-label.json', import.meta.url));
  const face = await readFile(new URL('../../node_modules/@makersbrain/ui/fonts/plex-latin.woff2', import.meta.url));
  await page.goto('/');
  await page.locator('input[type=file][accept*="mb-label"]').setInputFiles({ name: 'f.mb-label.json', mimeType: 'application/json', buffer: fixture });
  await expect(page.locator('footer')).toContainText('Opened SDK compatibility');
  await page.getByText('Assets', { exact: true }).first().click();
  await page.locator('input[type=file][accept*=".ttf"]').setInputFiles({ name: 'plex-latin.woff2', mimeType: 'font/woff2', buffer: face });
  await page.getByText('Layers', { exact: true }).first().click();
  await page.locator('.element.text[data-id="text-1"]').click({ force: true });
  await page.getByRole('combobox', { name: 'Font' }).selectOption({ index: 1 });
  await page.getByText('File', { exact: true }).click();
  const download = page.waitForEvent('download', { timeout: 10000 }).catch(() => undefined);
  await page.getByRole('button', { name: 'Export PNG' }).click();
  await page.waitForTimeout(2000);
  console.log('FOOTER:', await page.locator('footer').first().innerText());
  console.log('DOWNLOAD:', (await download)?.suggestedFilename() ?? 'none');
});
