// SPDX-License-Identifier: AGPL-3.0-or-later
import type { DirectTransport } from './direct.js';
export type DeviceErrorCode='unsupported'|'insecure-context'|'permission-denied'|'device-disconnected'|'response-timeout'|'notification-unavailable'|'transport-failure';
export class DeviceError extends Error { constructor(readonly code:DeviceErrorCode,message:string,options?:ErrorOptions){super(message,options);this.name='DeviceError'} }
const classify=(error:unknown,action:string)=>{if(error instanceof DeviceError)return error;const source=error as DOMException;if(source?.name==='NotFoundError'||source?.name==='SecurityError')return new DeviceError('permission-denied',`${action} was denied or no device was selected.`,{cause:error});if(source?.name==='NetworkError')return new DeviceError('device-disconnected','The printer disconnected. Reconnect it and inspect the job before retrying.',{cause:error});return new DeviceError('transport-failure',`${action} failed: ${source?.message??String(error)}`,{cause:error})};
interface BleCharacteristic {startNotifications():Promise<BleCharacteristic>;writeValueWithoutResponse?(data:BufferSource):Promise<void>;writeValue?(data:BufferSource):Promise<void>;addEventListener(type:string,listener:(event:Event)=>void):void}
interface BleServer {getPrimaryService(id:string):Promise<{getCharacteristic(id:string):Promise<BleCharacteristic>}>;disconnect():void}
interface BleDevice {gatt?:{connected:boolean;connect():Promise<BleServer>;disconnect():void}}
interface BluetoothApi {requestDevice(options:unknown):Promise<BleDevice>}
export interface BluetoothOptions {service:string;writeCharacteristic:string;notifyCharacteristic?:string;filters?:unknown[];physicalWriteLimit?:number}
export class WebBluetoothTransport implements DirectTransport {
  readonly kind='bluetooth' as const;readonly physicalWriteLimit:number;private device?:BleDevice;private server?:BleServer;private writer?:BleCharacteristic;private notifier?:BleCharacteristic;private replies:Uint8Array[]=[];private waiters:((value:Uint8Array)=>void)[]=[];
  constructor(private options:BluetoothOptions,private bluetooth:BluetoothApi|undefined=(navigator as Navigator&{bluetooth?:BluetoothApi}).bluetooth){this.physicalWriteLimit=options.physicalWriteLimit??20}
  async connect(){if(!isSecureContext)throw new DeviceError('insecure-context','Web Bluetooth requires HTTPS or localhost.');if(!this.bluetooth)throw new DeviceError('unsupported','Web Bluetooth is unavailable in this browser.');try{this.device=await this.bluetooth.requestDevice({filters:this.options.filters??[{services:[this.options.service]}],optionalServices:[this.options.service]});if(!this.device.gatt)throw new Error('Selected device has no GATT server');this.server=await this.device.gatt.connect();const service=await this.server.getPrimaryService(this.options.service);this.writer=await service.getCharacteristic(this.options.writeCharacteristic);if(this.options.notifyCharacteristic)this.notifier=await service.getCharacteristic(this.options.notifyCharacteristic)}catch(error){throw classify(error,'Bluetooth connection')}}
  async subscribe(_channel:string){if(!this.notifier)throw new DeviceError('notification-unavailable','This printer definition has no notification characteristic.');await this.notifier.startNotifications();this.notifier.addEventListener('characteristicvaluechanged',(event)=>{const view=(event.target as EventTarget&{value?:DataView}).value;if(!view)return;const data=new Uint8Array(view.buffer.slice(view.byteOffset,view.byteOffset+view.byteLength));const waiter=this.waiters.shift();waiter?waiter(data):this.replies.push(data)})}
  async write(data:Uint8Array){if(!this.writer)throw new DeviceError('device-disconnected','Bluetooth printer is not connected.');const buffer=new Uint8Array(data).buffer;try{if(this.writer.writeValueWithoutResponse)await this.writer.writeValueWithoutResponse(buffer);else if(this.writer.writeValue)await this.writer.writeValue(buffer);else throw new Error('Characteristic is not writable')}catch(error){throw classify(error,'Bluetooth write')}}
  async waitResponse(_channel:string,timeoutMs:number,_validation?:string,signal?:AbortSignal){const queued=this.replies.shift();if(queued)return queued;return await new Promise<Uint8Array>((resolve,reject)=>{const waiter=(value:Uint8Array)=>{cleanup();resolve(value)};const abort=()=>{cleanup();reject(new DOMException('Print cancelled.','AbortError'))};const cleanup=()=>{clearTimeout(timer);this.waiters=this.waiters.filter(item=>item!==waiter);signal?.removeEventListener('abort',abort)};const timer=setTimeout(()=>{cleanup();reject(new DeviceError('response-timeout',`Printer response timed out after ${timeoutMs} ms.`))},timeoutMs);signal?.addEventListener('abort',abort,{once:true});this.waiters.push(waiter)})}
  async disconnect(){this.device?.gatt?.disconnect();this.device=undefined;this.writer=undefined;this.notifier=undefined}
}
interface UsbDevice {opened:boolean;configuration?:{interfaces:{interfaceNumber:number;alternates:{alternateSetting:number;endpoints:{endpointNumber:number;direction:'in'|'out';type:string;packetSize:number}[]}[]}[]};open():Promise<void>;selectConfiguration(value:number):Promise<void>;claimInterface(value:number):Promise<void>;selectAlternateInterface(value:number,alternate:number):Promise<void>;transferOut(endpoint:number,data:BufferSource):Promise<unknown>;transferIn(endpoint:number,length:number):Promise<{data?:DataView}>;close():Promise<void>}
interface UsbApi {requestDevice(options:unknown):Promise<UsbDevice>}
export interface UsbOptions {filters:{vendorId:number;productId?:number}[];configurationValue?:number;interfaceNumber?:number;outEndpoint?:number;inEndpoint?:number;physicalWriteLimit?:number}
export class WebUsbTransport implements DirectTransport {readonly kind='usb' as const;readonly physicalWriteLimit:number;private device?:UsbDevice;private outEndpoint?:number;private inEndpoint?:number;
  constructor(private options:UsbOptions,private usb:UsbApi|undefined=(navigator as Navigator&{usb?:UsbApi}).usb){this.physicalWriteLimit=options.physicalWriteLimit??1024}
  async connect(){if(!isSecureContext)throw new DeviceError('insecure-context','WebUSB requires HTTPS or localhost.');if(!this.usb)throw new DeviceError('unsupported','WebUSB is unavailable in this browser.');try{this.device=await this.usb.requestDevice({filters:this.options.filters});await this.device.open();if(!this.device.configuration)await this.device.selectConfiguration(this.options.configurationValue??1);const iface=this.options.interfaceNumber??this.device.configuration?.interfaces[0]?.interfaceNumber??0;await this.device.claimInterface(iface);const alternate=this.device.configuration?.interfaces.find(item=>item.interfaceNumber===iface)?.alternates[0];if(alternate&&alternate.alternateSetting)await this.device.selectAlternateInterface(iface,alternate.alternateSetting);this.outEndpoint=this.options.outEndpoint??alternate?.endpoints.find(item=>item.direction==='out')?.endpointNumber;this.inEndpoint=this.options.inEndpoint??alternate?.endpoints.find(item=>item.direction==='in')?.endpointNumber;if(this.outEndpoint===undefined)throw new Error('No bulk OUT endpoint')}catch(error){throw classify(error,'USB connection')}}
  async subscribe(_channel:string){if(this.inEndpoint===undefined)throw new DeviceError('notification-unavailable','This USB printer has no response endpoint.')}
  async write(data:Uint8Array){if(!this.device||this.outEndpoint===undefined)throw new DeviceError('device-disconnected','USB printer is not connected.');try{await this.device.transferOut(this.outEndpoint,new Uint8Array(data).buffer)}catch(error){throw classify(error,'USB write')}}
  async waitResponse(_channel:string,timeoutMs:number,_validation?:string,signal?:AbortSignal){if(!this.device||this.inEndpoint===undefined)throw new DeviceError('notification-unavailable','This USB printer has no response endpoint.');const read=this.device.transferIn(this.inEndpoint,this.physicalWriteLimit).then(result=>result.data?new Uint8Array(result.data.buffer.slice(result.data.byteOffset,result.data.byteOffset+result.data.byteLength)):new Uint8Array());return await Promise.race([read,new Promise<Uint8Array>((_,reject)=>{const timer=setTimeout(()=>reject(new DeviceError('response-timeout',`Printer response timed out after ${timeoutMs} ms.`)),timeoutMs);signal?.addEventListener('abort',()=>{clearTimeout(timer);reject(new DOMException('Print cancelled.','AbortError'))},{once:true})})])}
  async disconnect(){if(this.device?.opened)await this.device.close();this.device=undefined}
}
