// SPDX-License-Identifier: AGPL-3.0-or-later
import { describe,expect,it } from 'vitest';
import { addElement,addResource,alignElements,alignElementsToBounds,assertGroupInvariants,defaultDocument,distributeElements,DocumentHistory,duplicateElements,groupElements,moveElements,patchElement,removeElements,resizeElements,toSdkDocument,ungroup,type LabelElement } from '../src/index.js';
const shape=(id:string,x:number):LabelElement=>({id,name:id,type:'rectangle',transform:{x,y:1,width:5,height:5,rotation:0},zIndex:x,visible:true,locked:false,strokeWidth:.2,filled:false});
describe('editor commands and history',()=>{
  it('undoes and redoes immutable edits',()=>{const original=defaultDocument('2026-01-01T00:00:00Z');const history=new DocumentHistory(original);history.execute(addElement(shape('a',2)));history.execute(moveElements(['a'],{x:3,y:4}));expect(history.document.elements[0].transform.x).toBe(5);expect(history.undo().document.elements[0].transform.x).toBe(2);expect(history.redo().document.elements[0].transform.x).toBe(5);expect(original.elements).toHaveLength(0)});
  it('does not record no-op commands and coalesces consecutive moves',()=>{const document=defaultDocument('2026-01-01T00:00:00Z');document.elements=[shape('a',2)];document.elements[0].locked=true;const history=new DocumentHistory(document);history.execute(moveElements(['a'],{x:1,y:1}));expect(history.state.canUndo).toBe(false);document.elements[0].locked=false;history.replace(document);history.execute(moveElements(['a'],{x:1,y:0}));history.execute(moveElements(['a'],{x:2,y:0}));expect(history.document.elements[0].transform.x).toBe(5);expect(history.undo().document.elements[0].transform.x).toBe(2)});
  it('aligns, distributes, groups, and removes selections',()=>{let doc=defaultDocument();doc.elements=[shape('a',0),shape('b',10),shape('c',30)];doc=alignElements(['a','b','c'],'top').apply(doc);doc=distributeElements(['a','b','c'],'horizontal').apply(doc);expect(doc.elements[1].transform.x).toBe(15);doc=groupElements(['a','b']).apply(doc);const group=doc.elements.find(item=>item.type==='group');expect(group&&group.type==='group'&&group.childIds).toEqual(['a','b']);doc=removeElements(['a']).apply(doc);expect(doc.elements.some(item=>item.id==='a')).toBe(false)});
  it('allocates a stable group identity before applying the command',()=>{const original=defaultDocument();original.elements=[shape('a',0),shape('b',10)];const command=groupElements(['a','b']);const first=command.apply(original);const second=command.apply(original);expect(first.elements.find(item=>item.type==='group')?.id).toBe(command.createdId);expect(second.elements.find(item=>item.type==='group')?.id).toBe(command.createdId)});
  it('moves a selected group and its children as one unit',()=>{let doc=defaultDocument();doc.elements=[shape('a',0),shape('b',10)];doc=groupElements(['a','b']).apply(doc);const group=doc.elements.find(item=>item.type==='group')!;doc=moveElements([group.id],{x:2,y:-1}).apply(doc);expect(doc.elements.find(item=>item.id==='a')?.transform).toMatchObject({x:2,y:0});expect(doc.elements.find(item=>item.id==='b')?.transform).toMatchObject({x:12,y:0});expect(doc.elements.find(item=>item.id===group.id)?.transform).toMatchObject({x:2,y:0})});
  it('resizes and aligns a selected group with all of its children',()=>{let doc=defaultDocument();doc.elements=[shape('a',0),shape('b',10)];doc=groupElements(['a','b']).apply(doc);const group=doc.elements.find(item=>item.type==='group')!;doc=resizeElements([group.id],{x:0,y:1,width:30,height:10}).apply(doc);expect(doc.elements.find(item=>item.id==='a')?.transform).toMatchObject({x:0,width:10,height:10});expect(doc.elements.find(item=>item.id==='b')?.transform).toMatchObject({x:20,width:10,height:10});doc=alignElementsToBounds([group.id],'right',{x:0,y:0,width:50,height:30}).apply(doc);expect(doc.elements.find(item=>item.id===group.id)?.transform.x).toBe(20);expect(doc.elements.find(item=>item.id==='a')?.transform.x).toBe(20);expect(doc.elements.find(item=>item.id==='b')?.transform.x).toBe(40)});
  it('asks the printer to preserve the aspect ratio of artwork the canvas letterboxes',()=>{const doc=defaultDocument();doc.resources=[{id:'art',name:'art.svg',mimeType:'image/svg+xml',data:''} as never];const base={transform:{x:1,y:1,width:20,height:10,rotation:0},zIndex:0,visible:true,locked:false};doc.elements=[{...base,id:'svg',name:'svg',type:'svg',resourceId:'art'},{...base,id:'contain',name:'contain',type:'image',resourceId:'art',fit:'contain'},{...base,id:'stretch',name:'stretch',type:'image',resourceId:'art',fit:'stretch'},{...base,id:'zoned',name:'zoned',type:'svg',resourceId:'art',constraints:[{kind:'zone',value:'right'}]}];const canonical=toSdkDocument(doc);const constraints=(id:string)=>canonical.elements.find(item=>item.id===id)?.constraints;expect(constraints('svg')).toMatchObject({preserveAspect:true});expect(constraints('contain')).toMatchObject({preserveAspect:true});expect(constraints('stretch')).toBeNull();expect(constraints('zoned')).toMatchObject({preserveAspect:true,zone:'right'})});
  it('serializes logical group containers without translating their root-coordinate children twice',()=>{let doc=defaultDocument();doc.elements=[shape('a',0),shape('b',10)];doc=groupElements(['a','b']).apply(doc);const group=doc.elements.find(item=>item.type==='group')!;doc=alignElementsToBounds([group.id],'right',{x:0,y:0,width:50,height:30}).apply(doc);const canonical=toSdkDocument(doc);const encodedGroup=canonical.elements.find(item=>item.id===group.id)!;expect(encodedGroup.transform).toMatchObject({x:0,y:0,rotationMillidegrees:0});expect(canonical.elements.find(item=>item.id==='a')?.transform).toMatchObject({x:35000});expect(canonical.elements.find(item=>item.id==='b')?.transform).toMatchObject({x:45000})});
  it('aligns and resizes zone-local elements in root coordinates without applying the zone twice',()=>{let doc=defaultDocument();const zone={id:'right',name:'Right',x:20,y:5,width:20,height:15};doc.media.zones=[zone];const zoned=shape('a',3);zoned.constraints=[{kind:'zone',value:'right'}];doc.elements=[zoned];doc=alignElementsToBounds(['a'],'left',zone).apply(doc);expect(doc.elements[0].transform.x).toBe(0);doc=alignElementsToBounds(['a'],'bottom',zone).apply(doc);expect(doc.elements[0].transform.y).toBe(10);doc=resizeElements(['a'],{x:20,y:5,width:10,height:8}).apply(doc);expect(doc.elements[0].transform).toMatchObject({x:0,y:0,width:10,height:8})});
  it('calculates group bounds from zone-local children in root coordinates',()=>{let doc=defaultDocument();doc.media.zones=[{id:'right',name:'Right',x:20,y:5,width:20,height:15}];const a=shape('a',1);const b=shape('b',9);a.constraints=[{kind:'zone',value:'right'}];b.constraints=[{kind:'zone',value:'right'}];doc.elements=[a,b];const command=groupElements(['a','b']);doc=command.apply(doc);expect(doc.elements.find(item=>item.id===command.createdId)?.transform).toMatchObject({x:21,y:6,width:13,height:5})});
  it('aligns a group of zone-local children inside that zone',()=>{let doc=defaultDocument();const zone={id:'right',name:'Right',x:20,y:5,width:20,height:15};doc.media.zones=[zone];const a=shape('a',1);const b=shape('b',9);a.constraints=[{kind:'zone',value:'right'}];b.constraints=[{kind:'zone',value:'right'}];doc.elements=[a,b];const command=groupElements(['a','b']);doc=command.apply(doc);doc=alignElementsToBounds([command.createdId],'right',zone).apply(doc);expect(doc.elements.find(item=>item.id===command.createdId)?.transform.x).toBe(27);expect(doc.elements.find(item=>item.id==='a')?.transform.x).toBe(7);expect(doc.elements.find(item=>item.id==='b')?.transform.x).toBe(15)});
  it('ungroups surviving children when their group is deleted',()=>{let doc=defaultDocument();doc.elements=[shape('a',0),shape('b',10)];doc=groupElements(['a','b']).apply(doc);const group=doc.elements.find(item=>item.type==='group')!;doc=removeElements([group.id]).apply(doc);expect(doc.elements.map(item=>item.id)).toEqual(['a','b']);expect(doc.elements.every(item=>item.groupId===undefined)).toBe(true);expect(()=>assertGroupInvariants(doc)).not.toThrow()});
  it('duplicates a complete group subtree with internally consistent IDs',()=>{let doc=defaultDocument();doc.elements=[shape('a',0),shape('b',10)];doc=groupElements(['a','b']).apply(doc);const original=doc.elements.find(item=>item.type==='group')!;doc=duplicateElements([original.id]).apply(doc);const groups=doc.elements.filter(item=>item.type==='group');expect(groups).toHaveLength(2);const duplicate=groups.find(item=>item.id!==original.id)!;expect(duplicate.childIds).toHaveLength(2);expect(duplicate.childIds).not.toEqual(original.childIds);for(const id of duplicate.childIds)expect(doc.elements.find(item=>item.id===id)?.groupId).toBe(duplicate.id);expect(()=>assertGroupInvariants(doc)).not.toThrow()});
  it('promotes children into the parent when ungrouping a nested group',()=>{let doc=defaultDocument();doc.elements=[shape('a',0),shape('b',10),shape('c',20)];doc=groupElements(['a','b']).apply(doc);const inner=doc.elements.find(item=>item.type==='group')!;doc=groupElements([inner.id,'c']).apply(doc);const outer=doc.elements.find(item=>item.type==='group'&&item.id!==inner.id)!;doc=ungroup(inner.id).apply(doc);const savedOuter=doc.elements.find(item=>item.id===outer.id);expect(savedOuter?.type==='group'&&savedOuter.childIds).toEqual(['a','b','c']);expect(doc.elements.find(item=>item.id==='a')?.groupId).toBe(outer.id);expect(()=>assertGroupInvariants(doc)).not.toThrow()});
  it('rejects generic patches to identity and group links',()=>{let doc=defaultDocument();doc.elements=[shape('a',0)];expect(()=>patchElement('a',{id:'replacement'}).apply(doc)).toThrow(/dedicated command/);expect(()=>patchElement('a',{groupId:'missing'}).apply(doc)).toThrow(/dedicated command/)});
  it('keeps distinct resource IDs when identical image bytes are placed again',()=>{let doc=defaultDocument();const first={id:'image-1',name:'photo.png',mimeType:'image/png',sha256:'same-content',data:'AA=='};const second={...first,id:'image-2'};doc=addResource(first).apply(doc);doc=addResource(second).apply(doc);expect(doc.resources.map(item=>item.id)).toEqual(['image-1','image-2'])});
});
