// SPDX-License-Identifier: AGPL-3.0-or-later
import {describe,expect,it,vi} from 'vitest';import {adaptSdkProtocolPlan,DeviceError,DirectPrintRoute,defaultDocument,inspectLaPosteSheet,selectedDocuments,type DirectTransport,type PrinterDefinition,type PrinterSdk,type ProtocolPlan} from '../src/index.js';
const printer:PrinterDefinition={id:'p',displayName:'P',dpi:203,protocols:['test'],media:{minWidth:1,maxWidth:100,minHeight:1,maxHeight:100}};
const sdk=(plan?:ProtocolPlan):PrinterSdk=>({validateCanonical:vi.fn(),validate:vi.fn(),render:vi.fn(),exportPng:vi.fn(),exportPdf:vi.fn(),printerDefinitions:async()=>[printer],importFirstPdfPage:vi.fn(),plan:async()=>plan!,inspectLaPoste:vi.fn(),laPosteSlotDocument:vi.fn()});
it('classifies a rejected first write as potentially accepted',async()=>{const transport:DirectTransport={kind:'usb',physicalWriteLimit:64,connect:async()=>{},disconnect:async()=>{},write:async()=>{throw new Error('transfer status unavailable')},subscribe:async()=>{},waitResponse:async()=>new Uint8Array([1])};const route=new DirectPrintRoute(sdk({protocol:'x',totalBytes:1,actions:[{type:'write',data:new Uint8Array([1]),chunkable:false,atomic:true,logicalChunkSize:64,delayAfterMs:0}]}),async()=>transport,'usb');const result=await route.print({document:defaultDocument(),printer,copies:1});expect(result.outcome).toBe('outcome-unknown');expect(result.bytesSent).toBe(0)});
describe('printing',()=>{it('serializes and physically chunks direct writes',async()=>{const writes:number[]=[];const transport:DirectTransport={kind:'bluetooth',physicalWriteLimit:4,negotiatedAttMtu:7,connect:async()=>{},disconnect:async()=>{},write:async data=>{writes.push(data.length)},subscribe:async()=>{},waitResponse:async()=>new Uint8Array()};const route=new DirectPrintRoute(sdk({protocol:'x',totalBytes:10,actions:[{type:'write',data:new Uint8Array(10),chunkable:true,atomic:false,logicalChunkSize:8,delayAfterMs:0}]}),async()=>transport,'bluetooth');const result=await route.print({document:defaultDocument(),printer,copies:1});expect(result.outcome).toBe('completed');expect(writes).toEqual([4,4,2])});it('marks an ambiguous accepted write as outcome unknown',async()=>{let count=0;const transport:DirectTransport={kind:'usb',physicalWriteLimit:4,connect:async()=>{},disconnect:async()=>{},write:async()=>{if(count++)throw new Error('gone')},subscribe:async()=>{},waitResponse:async()=>new Uint8Array()};const route=new DirectPrintRoute(sdk({protocol:'x',totalBytes:8,actions:[{type:'write',data:new Uint8Array(8),chunkable:true,atomic:false,logicalChunkSize:4,delayAfterMs:0}]}),async()=>transport,'usb');expect((await route.print({document:defaultDocument(),printer,copies:1})).outcome).toBe('outcome-unknown')})});
it('keeps Brother USB commands whole, chunks raster at 64 bytes, and tolerates absent status',async()=>{const writes:number[]=[];const transport:DirectTransport={kind:'usb',physicalWriteLimit:64,commandWriteLimit:1024,connect:async()=>{},disconnect:async()=>{},write:async data=>{writes.push(data.length)},subscribe:async()=>{},waitResponse:async()=>{throw new DeviceError('response-timeout','no status')}};const route=new DirectPrintRoute(sdk({protocol:'brother',totalBytes:330,actions:[{type:'write',data:new Uint8Array(200),chunkable:false,atomic:true,logicalChunkSize:200,delayAfterMs:0},{type:'wait-response',channel:'printer',timeoutMs:1,validate:'brother-status32'},{type:'write',data:new Uint8Array(130),chunkable:true,atomic:false,logicalChunkSize:1024,delayAfterMs:0}]}),async()=>transport,'usb');const result=await route.print({document:defaultDocument(),printer,copies:1});expect(result.outcome).toBe('completed');expect(writes).toEqual([200,64,64,2])});
it('adapts sibling SDK action names without losing pacing',()=>{const plan=adaptSdkProtocolPlan('m-series',[{action:'raster-write',bytes:[1,2,3],logical_chunk:128,delay_after_each_physical_write_ms:20},{action:'wait-for-response',timeout_ms:500,fallback_delay_ms:500,validation:'any-notification'}]);expect(plan.totalBytes).toBe(3);expect(plan.actions).toEqual([{type:'write',data:new Uint8Array([1,2,3]),chunkable:true,atomic:false,logicalChunkSize:128,delayAfterMs:20},{type:'wait-response',channel:'printer',timeoutMs:500,fallbackDelayMs:500,validate:'any-notification'}])});
describe('La Poste workflow',()=>{it('normalizes SHEET and preserves slot order',async()=>{const fake=sdk();fake.inspectLaPoste=async(_,format)=>{expect(format).toBe('L24A_SHEET');return [{id:'b',sourcePage:2,slot:1,occupied:true,widthMm:63.5,heightMm:33.9,preview:{width:1,height:1,rgba:new Uint8Array()}},{id:'a',sourcePage:1,slot:3,occupied:true,widthMm:63.5,heightMm:33.9,preview:{width:1,height:1,rgba:new Uint8Array()}}]};fake.laPosteSlotDocument=async(_,__,slot)=>({...defaultDocument(),id:slot.id});const inspection=await inspectLaPosteSheet(fake,new Uint8Array(),'SHEET');expect((await selectedDocuments(fake,inspection)).map(doc=>doc.id)).toEqual(['a','b'])})});
