<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<script lang="ts">import type { EditorStore } from '../store.js';import type{PrinterSdk}from'../print/types.js'; import {addElement,groupElements,moveElements,removeElements,ungroup} from '../commands.js';import {copyElements,pasteElements} from '../clipboard.js'; import Canvas from './Canvas.svelte';import Inspector from './Inspector.svelte';import Layers from './Layers.svelte';import DataPanel from './DataPanel.svelte';import AssetPanel from './AssetPanel.svelte';import MediaPanel from './MediaPanel.svelte';import Toolbar from './Toolbar.svelte'; export let editor:EditorStore;export let sdk:PrinterSdk|undefined=undefined;
function keys(event:KeyboardEvent){const target=event.target as HTMLElement;if(['INPUT','TEXTAREA','SELECT'].includes(target.tagName))return;const modifier=event.ctrlKey||event.metaKey;
  if(modifier&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?editor.redo():editor.undo()}else if(modifier&&event.key.toLowerCase()==='y'){event.preventDefault();editor.redo()}
  else if(modifier&&event.key.toLowerCase()==='a'){event.preventDefault();editor.select($editor.document.elements.map(e=>e.id))}else if(modifier&&event.key.toLowerCase()==='c'){event.preventDefault();copyElements($editor.document.elements,$editor.selection)}
  else if(modifier&&event.key.toLowerCase()==='v'){event.preventDefault();const items=pasteElements();for(const item of items)editor.execute(addElement(item));editor.select(items.map(i=>i.id))}
  else if(modifier&&event.key.toLowerCase()==='g'){event.preventDefault();if(event.shiftKey){for(const item of $editor.selectedElements)if(item.type==='group')editor.execute(ungroup(item.id))}else editor.execute(groupElements($editor.selection))}
  else if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();editor.execute(removeElements($editor.selection));editor.clearSelection()}
  else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const step=event.shiftKey?1:.1;editor.execute(moveElements($editor.selection,{x:event.key==='ArrowLeft'?-step:event.key==='ArrowRight'?step:0,y:event.key==='ArrowUp'?-step:event.key==='ArrowDown'?step:0}))}}
</script>
<svelte:window on:keydown={keys}/><div class="editor"><header><slot name="header"/></header><Toolbar {editor}/><main><div class="canvas"><Canvas {editor} {sdk}/></div><aside><Layers {editor}/><Inspector {editor}/><MediaPanel {editor}/><DataPanel {editor}/><AssetPanel {editor} {sdk}/><slot name="sidebar"/></aside></main></div>
<style>.editor{height:100%;display:flex;flex-direction:column;color:#17231c;background:#f7f4ed;font-family:Inter,system-ui,sans-serif}main{display:grid;grid-template-columns:minmax(0,1fr) 18rem;min-height:0;flex:1}.canvas{min-width:0}aside{overflow:auto;background:#fff}@media(max-width:760px){main{grid-template-columns:1fr;grid-template-rows:minmax(20rem,1fr) auto}aside{max-height:16rem;display:grid;grid-template-columns:1fr 1fr}}</style>
