<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<script lang="ts">import {exportLaPostePdf,inspectLaPosteSheet,printLaPoste,selectLaPosteSlots,type LaPosteInspection} from '../laposte/workflow.js';import {LA_POSTE_FORMATS,type LaPosteFormat,type PrinterSdk,type PrintRequest,type PrintRoute} from '../print/types.js';export let sdk:PrinterSdk;export let route:PrintRoute|undefined;export let printRequest:Omit<PrintRequest,'document'>|undefined;let format:LaPosteFormat='L24A';let inspection:LaPosteInspection|undefined;let status='';
async function load(event:Event){try{const file=(event.currentTarget as HTMLInputElement).files?.[0];if(!file)return;status='Inspecting locally…';inspection=await inspectLaPosteSheet(sdk,new Uint8Array(await file.arrayBuffer()),format);status=`Found ${inspection.selected.size} occupied stamps.`}catch(error){status=error instanceof Error?error.message:String(error)}}
function toggle(id:string,checked:boolean){if(!inspection)return;const ids=new Set(inspection.selected);checked?ids.add(id):ids.delete(id);inspection=selectLaPosteSlots(inspection,ids)}
async function save(){if(!inspection)return;const data=await exportLaPostePdf(sdk,inspection);const anchor=document.createElement('a');anchor.href=URL.createObjectURL(new Blob([new Uint8Array(data).buffer],{type:'application/pdf'}));anchor.download='la-poste-labels.pdf';anchor.click();URL.revokeObjectURL(anchor.href)}
async function print(){if(!inspection||!route||!printRequest)return;const results=await printLaPoste(sdk,inspection,route,printRequest);status=`${results.filter(r=>r.outcome==='completed').length}/${inspection.selected.size} stamps printed.`}
</script>
<section><h2>La Poste sheets</h2><label>Format<select bind:value={format}>{#each LA_POSTE_FORMATS.filter(item=>item!=='SHEET') as item}<option>{item}</option>{/each}</select></label><label class="upload">Choose A4 PDF<input type="file" accept="application/pdf" on:change={load}></label><p aria-live="polite">{status}</p>{#if inspection}<div class="slots">{#each inspection.slots.filter(slot=>slot.occupied) as slot}<label><input type="checkbox" checked={inspection.selected.has(slot.id)} on:change={(e)=>toggle(slot.id,e.currentTarget.checked)}><span>Page {slot.sourcePage}, slot {slot.slot}<small>63.5 × 33.9 mm</small></span></label>{/each}</div><button on:click={save} disabled={!inspection.selected.size}>Export selected PDF</button><button on:click={print} disabled={!inspection.selected.size||!route||!printRequest}>Print selected</button>{/if}</section>
<style>section{padding:.75rem;border-top:1px solid #ddd}h2{font-size:.8rem;text-transform:uppercase}.upload{display:block;border:1px solid #bbb;border-radius:4px;padding:.4rem;margin:.4rem 0}.upload input{position:absolute;opacity:0;width:1px}.slots{display:grid;grid-template-columns:1fr 1fr;gap:.35rem;max-height:12rem;overflow:auto}.slots label{display:flex;background:#f7f4ed;padding:.3rem}.slots small{display:block}</style>
