<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<script lang="ts">
import{onMount}from'svelte';import type{EditorStore}from'../store.js';import type{PrinterDefinition,PrinterSdk}from'../print/types.js';import{updateDocument}from'../commands.js';import{uuid,type Media}from'../model.js';
export let editor:EditorStore;export let sdk:PrinterSdk|undefined=undefined;let printers:PrinterDefinition[]=[];
onMount(async()=>{if(sdk)printers=await sdk.printerDefinitions()});
const presets=[['50 × 30',50,30,203,'rectangle'],['La Poste',63.5,33.9,300,'rectangle'],['Round 50',50,50,203,'round']]as const;
function media(patch:Partial<Media>){const next={...$editor.document.media,...patch};if(patch.width||patch.height)next.printableBounds={x:0,y:0,width:next.width,height:next.height};editor.execute(updateDocument({media:next}))}
function preset(index:string){const p=presets[+index];if(p)media({width:p[1],height:p[2],dpi:p[3],shape:p[4]})}
function printerPreset(id:string){const p=printers.find(item=>item.id===id);if(p)media({width:Math.min(p.media.maxWidth,Math.max(p.media.minWidth,$editor.document.media.width)),height:Math.min(p.media.maxHeight,Math.max(p.media.minHeight,$editor.document.media.height)),dpi:p.dpi})}
function addZone(clone=false){const zones=$editor.document.media.zones??[];const source=zones[0];media({zones:[...zones,{id:uuid(),name:`Zone ${zones.length+1}`,x:source?.x??0,y:source?.y??0,width:source?.width??$editor.document.media.width,height:source?.height??$editor.document.media.height,...clone&&source?{cloneOf:source.id}:{}}]})}
function edit(id:string,patch:Record<string,unknown>){media({zones:($editor.document.media.zones??[]).map(zone=>zone.id===id?{...zone,...patch}:zone)})}function remove(id:string){media({zones:($editor.document.media.zones??[]).filter(zone=>zone.id!==id).map(zone=>zone.cloneOf===id?{...zone,cloneOf:undefined}:zone)})}
</script>
{#if printers.length}<section class="capabilities"><label>Printer capability<select on:change={e=>printerPreset(e.currentTarget.value)}><option value="">Choose printer limits</option>{#each printers as printer}<option value={printer.id}>{printer.displayName} · {printer.dpi} dpi · {printer.media.minWidth}–{printer.media.maxWidth} mm</option>{/each}</select></label></section>{/if}
<section><h2>Media & zones</h2><label>Preset<select on:change={e=>preset(e.currentTarget.value)}><option value="">Custom</option>{#each presets as item,index}<option value={index}>{item[0]}</option>{/each}</select></label><div class="grid">{#each ['width','height','dpi'] as key}<label>{key}<input type="number" min="1" step=".1" value={$editor.document.media[key as 'width']} on:change={e=>media({[key]:+e.currentTarget.value})}></label>{/each}<label>Shape<select value={$editor.document.media.shape} on:change={e=>media({shape:e.currentTarget.value as Media['shape']})}><option>rectangle</option><option>round</option><option>continuous</option></select></label></div><button on:click={()=>addZone()}>Add independent zone</button><button on:click={()=>addZone(true)} disabled={!$editor.document.media.zones?.length}>Add cloned zone</button>{#each $editor.document.media.zones??[] as zone}<fieldset><legend>{zone.name}</legend><div class="grid"><label>Name<input value={zone.name} on:change={e=>edit(zone.id,{name:e.currentTarget.value})}></label>{#each ['x','y','width','height'] as key}<label>{key}<input type="number" step=".1" value={zone[key as 'x']} on:change={e=>edit(zone.id,{[key]:+e.currentTarget.value})}></label>{/each}<label>Mode<select value={zone.cloneOf??''} on:change={e=>edit(zone.id,{cloneOf:e.currentTarget.value||undefined})}><option value="">Independent</option>{#each ($editor.document.media.zones??[]).filter(item=>item.id!==zone.id) as source}<option value={source.id}>Clone {source.name}</option>{/each}</select></label></div><button on:click={()=>remove(zone.id)}>Remove</button></fieldset>{/each}</section>
<style>section{padding:.7rem .75rem;border-top:1px solid var(--mble-border,#e5dfd5)}h2{margin:0 0 .5rem;color:var(--mble-text-muted,#59635e);font-size:.75rem;font-weight:600}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.4rem}label{display:flex;flex-direction:column;font-size:.75rem}fieldset{margin:.5rem 0}</style>
