<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<script lang="ts">
  import { BatchPanel,DirectPrintPanel,JobRecoveryPanel,JobJournal,LabelEditor,LaPostePanel,LocalServicePanel,createEditorStore,defaultDocument,EditorDatabase,createAutosaver,openDocument,saveDocument,LocalApiPrintRoute,type LocalApiConnection,type PrinterSdk,type PrinterDefinition,type PrintProgress,type PrintRoute } from '@makersbrain/label-editor'; import {loadPrinterSdk} from './sdk.js';
  const editor=createEditorStore(defaultDocument()); const database=new EditorDatabase(); const autosave=createAutosaver(database); let status='Ready'; let sdk:PrinterSdk|undefined;let printers:PrinterDefinition[]=[];let printerId='';let progress:PrintProgress|undefined;let apiToken=localStorage.getItem('mb-local-api-token')??'';let connectionId=localStorage.getItem('mb-local-api-connection')??'';let localConnection:LocalApiConnection|undefined;let handle:unknown;let online=navigator.onLine;const localRoute=new LocalApiPrintRoute({token:()=>apiToken,connection:()=>localConnection,journal:new JobJournal(database)});let selectedRoute:PrintRoute=localRoute;
  async function restoreAutosave(){try{const recovered=await database.latestAutosave();if(recovered){editor.replace(recovered.document);status=`Recovered autosave from ${new Date(recovered.savedAt).toLocaleTimeString()}`;}}catch(error){status=`Autosave recovery unavailable: ${message(error)}`;}}
  async function restorePreferences(){const preferences=await database.getPreferences();if(preferences){editor.setView({gridSize:preferences.gridSize,showGrid:preferences.showGrid,showRulers:preferences.showRulers,snapping:preferences.snapping});printerId=preferences.defaultPrinterId??printerId}}
  void restoreAutosave();void restorePreferences();editor.subscribe(state=>{autosave(state.document);void database.savePreferences({gridSize:state.view.gridSize,showGrid:state.view.showGrid,showRulers:state.view.showRulers,snapping:state.view.snapping,defaultPrinterId:printerId||undefined,defaultRoute:'local-api',theme:'system'});if(state.document.template)void database.saveTemplate(state.document.id,state.document.template);void database.saveRecent({id:state.document.id,kind:'document',openedAt:new Date().toISOString()})});
  async function open(event?:Event){try{const file=(event?.currentTarget as HTMLInputElement)?.files?.[0];const opened=await openDocument(file);editor.replace(opened.document);handle=opened.handle;status=`Opened ${opened.document.title}`;}catch(error){status=message(error)}}
  async function save(){try{handle=await saveDocument($editor.document,undefined,handle as never);await database.saveDocument($editor.document);status='Saved';}catch(error){status=message(error)}}
  async function ensureSdk(){if(!sdk){status='Loading printer SDK…';sdk=await loadPrinterSdk();printers=await sdk.printerDefinitions();printerId||=printers[0]?.id??'';}return sdk}
  async function preview(){try{const loaded=await ensureSdk();const raster=await loaded.render($editor.document,{exactThermal:true});status=`Thermal preview: ${raster.width} × ${raster.height} dots`;}catch(error){status=message(error)}}
  async function exportFile(kind:'png'|'pdf'){try{const loaded=await ensureSdk();const data=kind==='png'?await loaded.exportPng($editor.document):await loaded.exportPdf([$editor.document]);const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([data.slice().buffer],{type:kind==='png'?'image/png':'application/pdf'}));link.download=`label.${kind}`;link.click();URL.revokeObjectURL(link.href);status=`Exported ${kind.toUpperCase()}.`}catch(error){status=message(error)}}
  async function print(){try{await ensureSdk();const printer=printers.find(item=>item.id===printerId);if(!printer)throw new Error('Select a printer model.');status='Printing…';const result=await localRoute.print({document:$editor.document,printer,copies:1,onProgress:value=>progress=value});status=result.outcome==='completed'?`Printed ${result.bytesSent} bytes`:`${result.outcome}: ${result.error??'Check the printer before retrying.'}`;}catch(error){status=message(error)}}
  function storeToken(){localStorage.setItem('mb-local-api-token',apiToken);status='Local service token stored only in this browser.'}
  function acceptToken(token:string){apiToken=token;storeToken()}
  function acceptConnection(connection:LocalApiConnection|undefined){localConnection=connection;connectionId=connection?.id??'';if(connection){localStorage.setItem('mb-local-api-connection',connection.id);selectedRoute=localRoute}else localStorage.removeItem('mb-local-api-connection');status=connection?`Selected ${connection.id} via ${connection.transport.kind}.`:'Select a persisted local printer connection.'}
  async function retryRecovered(job:import('@makersbrain/label-editor').PersistedJob){if(job.route!=='local-api'){status='Reconnect through Direct browser print to start a new explicit hardware job; the interrupted job was not replayed.';return}const document=await database.get<import('@makersbrain/label-editor').LabelDocument>('documents',job.documentId);const printer=printers.find(item=>item.id===printerId);if(!document||!printer||!localConnection){status='Open the saved document and select its printer connection before explicitly retrying.';return}const result=await localRoute.print({document,printer,copies:1});status=`Explicit recovery attempt: ${result.outcome}.`}
  const message=(error:unknown)=>error instanceof Error?error.message:String(error);
</script>
<svelte:window on:online={()=>online=true} on:offline={()=>online=false}/><div class="app"><LabelEditor {editor} {sdk}><div slot="header" class="appbar"><strong>MakersBrain Label Editor</strong><label class="file">Open<input type="file" accept=".mb-label.json,application/json" on:change={open}></label><button on:click={save}>Save</button><button on:click={preview}>Thermal preview</button><button on:click={()=>exportFile("png")}>Export PNG</button><button on:click={()=>exportFile("pdf")}>Export PDF</button><select bind:value={printerId} on:focus={()=>void ensureSdk()} aria-label="Printer model"><option value="">Printer model</option>{#each printers as printer}<option value={printer.id}>{printer.displayName}</option>{/each}</select><input class="token" type="password" bind:value={apiToken} on:change={storeToken} placeholder="Local API token" aria-label="Local service token"><button class="primary" on:click={print} disabled={!localConnection}>Print via local service</button></div><div slot="sidebar"><LocalServicePanel route={localRoute} onToken={acceptToken} onConnection={acceptConnection} selectedId={connectionId}/><JobRecoveryPanel {database} onRetry={retryRecovered}/>{#if sdk}<LaPostePanel {sdk} route={selectedRoute} printRequest={printers.find(item=>item.id===printerId)?{printer:printers.find(item=>item.id===printerId)!,copies:1}:undefined}/><BatchPanel document={$editor.document} {sdk} route={selectedRoute} printer={printers.find(item=>item.id===printerId)}/><DirectPrintPanel document={$editor.document} {sdk} printer={printers.find(item=>item.id===printerId)} {database} onRoute={route=>selectedRoute=route}/>{/if}</div></LabelEditor><footer aria-live="polite"><span class:offline={!online}>{online?'Online':'Offline — local editing and export remain available'}</span> · {status}{#if progress} · action {progress.action}/{progress.actions}, {progress.bytesSent}/{progress.totalBytes} bytes{/if}</footer></div>
<style>.app{height:100dvh;display:grid;grid-template-rows:minmax(0,1fr) auto}.appbar{display:flex;gap:.5rem;align-items:center;padding:.65rem 1rem;background:#236447;color:white}.appbar strong{margin-right:auto}.file{background:#fff;color:#17231c;border-radius:4px;padding:.35rem .55rem}.file input{position:absolute;opacity:0;width:1px}.token{width:8rem}.primary{background:#ed6146;color:white;border-color:#ed6146}footer{padding:.4rem 1rem;background:#17231c;color:white;font-size:.8rem}.offline{color:#ffc35b;font-weight:bold}@media(max-width:800px){.appbar{overflow:auto}.appbar strong{min-width:max-content}}</style>
