<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<script lang="ts">
  import {onMount} from 'svelte';
  import {BrandLockup} from '@makersbrain/ui/svelte';
  import { BatchPanel,CloudPrintClient,CloudPrintPanel,CloudPrintRoute,DirectPrintPanel,ExternalResourceConnectionManager,ExternalResourceConnectionsPanel,JobRecoveryPanel,JobJournal,LabelEditor,LaPostePanel,LocalServicePanel,SheetPanel,assetCatalogProviderFactory,createEditorStore,defaultDocument,downloadBytes,EditorDatabase,createAutosaver,openDocument,saveDocument,LocalApiPrintRoute,Modal,Menu,updateDocument,type CloudPrinter,type DocumentMaterializer,type ExternalResourceConnection,type ExternalResourceProvider,type LocalApiConnection,type PrinterSdk,type PrinterDefinition,type PrintProgress,type PrintRoute,type SheetExporter,type SheetFillOrder,type SheetLayoutPreset,type SheetPreferencesV1 } from '@makersbrain/label-editor'; import {loadPrinterSdk} from './sdk.js';
  const resourceConnectionsKey='mb-external-resource-connections-v1';const selectedResourceKey='mb-external-resource-selected-v1';const legacyAssetUrl=localStorage.getItem('mb-asset-catalog-url')??import.meta.env.VITE_ASSET_CATALOG_URL??'http://127.0.0.1:8766';const initialResourceConnections=readResourceConnections()??(legacyAssetUrl?[{version:1 as const,id:'default-asset-catalog',name:'MakersBrain assets',providerKind:'mbprint-asset-catalog',endpoint:legacyAssetUrl,enabled:true}]:[]);const resourceManager=new ExternalResourceConnectionManager([assetCatalogProviderFactory],initialResourceConnections,localStorage.getItem(selectedResourceKey)??'');const legacyAssetToken=localStorage.getItem('mb-asset-catalog-token')??'';if(legacyAssetToken&&resourceManager.selectedId())resourceManager.setSessionToken(resourceManager.selectedId(),legacyAssetToken);localStorage.removeItem('mb-asset-catalog-token');localStorage.removeItem('mb-asset-catalog-url');localStorage.setItem(resourceConnectionsKey,JSON.stringify(resourceManager.connections()));
  const editor=createEditorStore(defaultDocument()); const database=new EditorDatabase(); let status='Ready'; const autosave=createAutosaver(database,1500,error=>status=`Autosave unavailable: ${message(error)}`); let sdk:(PrinterSdk&SheetExporter&DocumentMaterializer)|undefined;let printers:PrinterDefinition[]=[];let printerId='';let progress:PrintProgress|undefined;let apiToken=localStorage.getItem('mb-local-api-token')??'';let resourceProvider:ExternalResourceProvider|undefined=resourceManager.selected();let connectionId=localStorage.getItem('mb-local-api-connection')??'';let localConnection:LocalApiConnection|undefined;let cloudUrl=localStorage.getItem('mb-cloud-print-url')??'';let cloudTenant=localStorage.getItem('mb-cloud-print-tenant')??'';let cloudToken='';let cloudPrinterId=localStorage.getItem('mb-cloud-print-printer')??'';let cloudPrinter:CloudPrinter|undefined;let cloudClient:CloudPrintClient|undefined;let cloudRoute:CloudPrintRoute|undefined;let directRoute:PrintRoute|undefined;let handle:unknown;let online=navigator.onLine;let theme:'system'|'light'|'dark'='system';let defaultRoute='local-api';let sheet:SheetPreferencesV1|undefined;let updateAvailable=false;const localRoute=new LocalApiPrintRoute({token:()=>apiToken,connection:()=>localConnection,journal:new JobJournal(database)});let selectedRoute:PrintRoute=localRoute;
  let printing=false;
  $: selectedPrinterDefinition=printers.find(item=>item.id===printerId);
  $: printAvailable=!!selectedPrinterDefinition&&(selectedRoute.id==='local-api'?!!localConnection&&localConnection.model===selectedPrinterDefinition.id:selectedRoute.id==='cloud-api'?!!cloudPrinter?.enabled&&cloudPrinter.model===selectedPrinterDefinition.id:!!directRoute);
  $: primaryPrintLabel=selectedRoute.id==='cloud-api'&&!cloudPrinter?.online?'Queue print':'Print';
  onMount(()=>{let unsubscribe:(()=>void)|undefined;let disposed=false;const update=()=>updateAvailable=true;window.addEventListener('mb-pwa-update',update);void start().then(value=>{if(disposed)value();else unsubscribe=value});return()=>{disposed=true;unsubscribe?.();window.removeEventListener('mb-pwa-update',update);void autosave.dispose()}});
  let dialog='';
  async function restoreAutosave(){try{const recovered=await database.latestAutosave();if(recovered){editor.replace(recovered.document);status=`Recovered autosave from ${new Date(recovered.savedAt).toLocaleTimeString()}`;}}catch(error){status=`Autosave recovery unavailable: ${message(error)}`;}}
  async function restorePreferences(){try{const preferences=await database.getPreferences();if(preferences){editor.setView({gridSize:preferences.gridSize,showGrid:preferences.showGrid,showRulers:preferences.showRulers,snapping:preferences.snapping});printerId=preferences.defaultPrinterId??printerId;theme=preferences.theme;defaultRoute=preferences.defaultRoute??defaultRoute;sheet=preferences.sheet?.version===1?preferences.sheet:undefined;applyTheme()}}catch(error){status=`Preferences unavailable: ${message(error)}`}}
  function preferences(){return{gridSize:$editor.view.gridSize,showGrid:$editor.view.showGrid,showRulers:$editor.view.showRulers,snapping:$editor.view.snapping,defaultPrinterId:printerId||undefined,defaultRoute,theme,sheet}}function applyTheme(){if(theme==='system')delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme=theme}function persistPreferences(){void database.savePreferences(preferences())}
  async function start(){await restorePreferences();await restoreAutosave();const unsubscribe=editor.subscribe(state=>{autosave(state.document);void database.savePreferences({...preferences(),gridSize:state.view.gridSize,showGrid:state.view.showGrid,showRulers:state.view.showRulers,snapping:state.view.snapping});if(state.document.template)void database.saveTemplate(state.document.id,state.document.template);void database.saveRecent({id:state.document.id,kind:'document',openedAt:new Date().toISOString()})});void ensureSdk().catch(error=>status=message(error));return unsubscribe}
  async function open(event?:Event){try{const file=(event?.currentTarget as HTMLInputElement)?.files?.[0];const loaded=await ensureSdk();const opened=await openDocument(file,loaded);editor.replace(opened.document);handle=opened.handle;status=`Opened ${opened.document.title}`;}catch(error){status=message(error)}}
  async function save(){try{handle=await saveDocument($editor.document,undefined,handle as never);await database.saveDocument($editor.document);status='Saved';}catch(error){status=message(error)}}
  async function ensureSdk(){if(!sdk){if(status==='Ready')status='Loading printer SDK…';sdk=await loadPrinterSdk(event=>{if(event.outcome==='failed')status=`Sheet ${event.operation} failed (${event.errorCode??'unknown'}).`;else if(event.operation==='export')status=`Sheet PDF built in ${Math.round(event.durationMs)} ms.`});printers=await sdk.printerDefinitions();printerId||=printers[0]?.id??'';}return sdk}
  function selectPrinter(id:string){printerId=id;persistPreferences();status=id?`Selected ${printers.find(item=>item.id===id)?.displayName??id}. Connect it in the printer panel.`:'Select a printer model.'}
  async function preview(){try{const loaded=await ensureSdk();const raster=await loaded.render($editor.document,{exactThermal:true});status=`Thermal preview: ${raster.width} × ${raster.height} dots`;}catch(error){status=message(error)}}
  async function exportFile(kind:'png'|'pdf'){try{const loaded=await ensureSdk();const data=kind==='png'?await loaded.exportPng($editor.document):await loaded.exportPdf([$editor.document]);downloadBytes(data,{filename:`label.${kind}`,mimeType:kind==='png'?'image/png':'application/pdf'});status=`Exported ${kind.toUpperCase()}.`}catch(error){status=message(error)}}
  async function print(){if(printing)return;printing=true;try{await ensureSdk();const printer=printers.find(item=>item.id===printerId);if(!printer)throw new Error('Select a printer model.');status=selectedRoute.id==='cloud-api'&&!cloudPrinter?.online?'Queueing cloud print…':'Printing…';progress=undefined;const result=await selectedRoute.print({document:$editor.document,printer,copies:1,onProgress:value=>progress=value});status=result.outcome==='completed'?`Printed ${result.bytesSent} bytes`:`${result.outcome}: ${result.error??'Check the printer before retrying.'}`;}catch(error){status=message(error)}finally{printing=false}}
  function storeToken(){localStorage.setItem('mb-local-api-token',apiToken);status='Local service token stored only in this browser.'}
  function storeResourceConnections(connections:ExternalResourceConnection[]){localStorage.setItem(resourceConnectionsKey,JSON.stringify(connections))}
  function selectResourceConnection(id:string){resourceManager.select(id);const selected=resourceManager.selectedId();resourceProvider=resourceManager.selected();if(selected)localStorage.setItem(selectedResourceKey,selected);else localStorage.removeItem(selectedResourceKey);status=resourceProvider?`Using external resources from ${resourceProvider.displayName}.`:'External resources are disabled.'}
  function acceptToken(token:string){apiToken=token;storeToken()}
  function acceptConnection(connection:LocalApiConnection|undefined,announce=true){localConnection=connection;connectionId=connection?.id??'';if(connection){localStorage.setItem('mb-local-api-connection',connection.id);printerId=connection.model;selectedRoute=localRoute;defaultRoute=localRoute.id;persistPreferences()}else localStorage.removeItem('mb-local-api-connection');if(announce)status=connection?`Selected ${connection.id} via ${connection.transport.kind}.`:'Select a persisted local printer connection.'}
  function acceptRoute(route:PrintRoute){directRoute=route;selectedRoute=route;defaultRoute=route.id;persistPreferences()}
  function chooseRoute(id:string){const route=id==='local-api'?localRoute:id==='cloud-api'?cloudRoute:directRoute;if(route){selectedRoute=route;defaultRoute=route.id;persistPreferences()}}
  async function connectCloud(){try{const baseUrl=cloudUrl.trim().replace(/\/+$/,'');const tenantId=cloudTenant.trim();if(!cloudToken.trim())throw new Error('Enter the print-only cloud token for this session.');const client=new CloudPrintClient({baseUrl,tenantId,getAccessToken:()=>cloudToken});await client.listPrinters();cloudUrl=baseUrl;cloudTenant=tenantId;cloudClient=client;cloudRoute=new CloudPrintRoute({client,printer:()=>cloudPrinter,journal:new JobJournal(database)});localStorage.setItem('mb-cloud-print-url',baseUrl);localStorage.setItem('mb-cloud-print-tenant',tenantId);selectedRoute=cloudRoute;defaultRoute=cloudRoute.id;persistPreferences();dialog='cloud';status='Cloud print session connected. The token will be forgotten when this page closes.'}catch(error){status=message(error)}}
  function endCloudSession(){cloudToken='';cloudClient=undefined;cloudRoute=undefined;cloudPrinter=undefined;if(selectedRoute.id==='cloud-api')selectedRoute=localRoute;status='Cloud print token cleared from this session.'}
  function acceptCloudPrinter(value:CloudPrinter|undefined){cloudPrinter=value;cloudPrinterId=value?.id??'';if(value){localStorage.setItem('mb-cloud-print-printer',value.id);printerId=value.model;selectedRoute=cloudRoute??selectedRoute;status=`Selected cloud printer ${value.displayName}${value.online?'':' (offline; current labels will queue)'}.`}else localStorage.removeItem('mb-cloud-print-printer')}
  async function retryRecovered(job:import('@makersbrain/label-editor').PersistedJob){if(job.route==='cloud-api'){if(!cloudRoute){dialog='cloud-connect';status='Reconnect the cloud session to resume this job.';return}const result=await cloudRoute.recover(job);status=`Cloud recovery: ${result.outcome}${result.error?`: ${result.error}`:''}.`;return}if(job.route!=='local-api'){status='Reconnect through Direct browser print to start a new explicit hardware job; the interrupted job was not replayed.';return}if(!localConnection){status='Reconnect the saved local printer before resuming this job.';return}const result=await localRoute.recover(job,undefined,value=>progress=value);status=`Local recovery: ${result.outcome}${result.error?`: ${result.error}`:''}.`}
  function applyPrinterMedia(media:{width:number;height:number;shape:'rectangle'|'round'|'continuous'}){const next={...$editor.document.media,width:media.width,height:media.height,shape:media.shape,printableBounds:{x:0,y:0,width:media.width,height:media.height}};editor.execute(updateDocument({media:next}));status=`Label media set to ${media.width} × ${media.height} mm from the printer.`}
  function rememberSheet(layoutId:string,fillOrder:SheetFillOrder,custom?:NonNullable<SheetLayoutPreset['grid']>){sheet={version:1,layoutId,fillOrder,...(custom?{lastCustomGrid:custom}:{})};persistPreferences()}
  function readResourceConnections():ExternalResourceConnection[]|undefined{try{const value=JSON.parse(localStorage.getItem(resourceConnectionsKey)??'null');return Array.isArray(value)?value:undefined}catch{return undefined}}
  const message=(error:unknown)=>error instanceof Error?error.message:String(error);
</script>
<svelte:window on:online={()=>online=true} on:offline={()=>online=false}/>
<div class="app">
  <LabelEditor {editor} {sdk} {resourceProvider} {printers} {printerId} onPrinter={selectPrinter}>
    <BrandLockup slot="brand" product="Label Editor" href="./"/>
    <Menu slot="menu-start" label="File">
      <button on:click={()=>open()}>Open picker</button>
      <label class="file">Upload<input type="file" accept=".mb-label.json,application/json" on:change={open}></label>
      <button on:click={save}>Save</button>
      <hr>
      <button on:click={preview}>Thermal preview</button>
      <button on:click={()=>exportFile("png")}>Export PNG</button>
      <button on:click={()=>exportFile("pdf")}>Export PDF</button>
      <hr>
      <label>Theme<select bind:value={theme} on:change={()=>{applyTheme();persistPreferences()}}><option>system</option><option>light</option><option>dark</option></select></label>
      <label>Local API token<input class="token" type="password" bind:value={apiToken} on:change={storeToken} placeholder="Token" aria-label="Local service token"></label>
      <hr>
      <button on:click={()=>dialog='external-resources'}>External resources…</button>
      {#if updateAvailable}<button on:click={()=>location.reload()}>Update application</button>{/if}
    </Menu>
    <Menu slot="menu-end" label="Print">
      <button on:click={print} disabled={printing||!printAvailable}>{primaryPrintLabel} current label via {selectedRoute.label}</button>
      <button on:click={()=>dialog='batch'}>Batch printing…</button>
      <button on:click={()=>dialog='sheet'}>Label sheet…</button>
      <button on:click={()=>dialog='laposte'}>La Poste sheets…</button>
      <hr>
      <button on:click={()=>dialog='service'}>Local service…</button>
      <button on:click={()=>dialog=cloudRoute?'cloud':'cloud-connect'}>Cloud printers…</button>
      {#if cloudRoute}<button on:click={endCloudSession}>End cloud session</button>{/if}
      <button on:click={()=>dialog='jobs'}>Recover print jobs…</button>
    </Menu>
    <svelte:fragment slot="actions">
      <span class="media-chip">{$editor.document.media.width} × {$editor.document.media.height} mm · {$editor.document.media.shape}</span>
      <select value={selectedRoute.id} on:change={event=>chooseRoute(event.currentTarget.value)} aria-label="Print route"><option value="local-api">Local service</option>{#if directRoute}<option value={directRoute.id}>Direct browser</option>{/if}{#if cloudRoute}<option value="cloud-api">Cloud</option>{/if}</select>
      <select value={printerId} on:change={event=>selectPrinter(event.currentTarget.value)} on:focus={()=>void ensureSdk()} aria-label="Printer model"><option value="">Printer model</option>{#each printers as printer}<option value={printer.id}>{printer.displayName}</option>{/each}</select>
      <button class="primary" on:click={print} disabled={printing||!printAvailable}>{primaryPrintLabel}</button>
    </svelte:fragment>
    <svelte:fragment slot="sidebar">{#if sdk}<DirectPrintPanel document={$editor.document} {sdk} printer={printers.find(item=>item.id===printerId)} {database} localRoute={localRoute} {localConnection} onLocalConnection={acceptConnection} onConfigureLocal={()=>dialog='service'} onSelectLocal={()=>chooseRoute('local-api')} onRoute={acceptRoute} onMedia={applyPrinterMedia}/>{:else}<p class="pending">Loading printer support…</p>{/if}</svelte:fragment>
  </LabelEditor>
  <footer aria-live="polite"><span class:offline={!online}>{online?'Online':'Offline — local editing and export remain available'}</span> · {status}{#if progress} · action {progress.action}/{progress.actions}, {progress.bytesSent}/{progress.totalBytes} bytes{/if}</footer>
  <Modal open={dialog==='service'} title="Local service" onClose={()=>dialog=''}><LocalServicePanel route={localRoute} onToken={acceptToken} onConnection={acceptConnection} selectedId={connectionId} paired={!!apiToken}/></Modal>
  <Modal open={dialog==='external-resources'} title="External resources" onClose={()=>dialog=''}><ExternalResourceConnectionsPanel manager={resourceManager} onChange={storeResourceConnections} onSelect={selectResourceConnection}/></Modal>
  <Modal open={dialog==='cloud-connect'} title="Connect cloud printing" onClose={()=>dialog=''}><section class="cloud-connect"><label>Cloud service URL<input type="url" bind:value={cloudUrl} placeholder="https://print.example.com"></label><label>Tenant ID<input bind:value={cloudTenant} spellcheck="false"></label><label>Print-only token<input type="password" bind:value={cloudToken} autocomplete="off"></label><button on:click={connectCloud} disabled={!cloudUrl.trim()||!cloudTenant.trim()||!cloudToken.trim()}>Connect for this session</button><p>The service URL and tenant are remembered. The token stays only in memory and is forgotten on reload.</p></section></Modal>
  <Modal open={dialog==='cloud'} title="Cloud printers" onClose={()=>dialog=''}>{#if cloudClient&&cloudRoute}<CloudPrintPanel client={cloudClient} route={cloudRoute} document={$editor.document} printer={printers.find(item=>item.id===printerId)} selectedId={cloudPrinterId} onPrinter={acceptCloudPrinter}/>{:else}<p class="pending">Connect a cloud print session first.</p>{/if}</Modal>
  <Modal open={dialog==='jobs'} title="Recover print jobs" onClose={()=>dialog=''}><JobRecoveryPanel {database} onRetry={retryRecovered}/></Modal>
  <Modal open={dialog==='batch'} title="Batch printing" onClose={()=>dialog=''}>{#if selectedRoute.id==='cloud-api'&&!cloudPrinter?.online}<p class="pending">Cloud batch printing requires the selected printer to be online. Queue only one current label while it is offline.</p>{/if}{#if sdk}<BatchPanel document={$editor.document} {sdk} materializer={sdk} route={selectedRoute.id==='cloud-api'&&!cloudPrinter?.online?undefined:selectedRoute} printer={printers.find(item=>item.id===printerId)}/>{:else}<p class="pending">Select a printer model to load the printer SDK first.</p>{/if}</Modal>
  <Modal open={dialog==='sheet'} title="Label sheet" onClose={()=>dialog=''}>{#if sdk}<SheetPanel document={$editor.document} exporter={sdk} materializer={sdk} initialPreferences={sheet} onLayout={rememberSheet} onStatus={value=>status=value}/>{:else}<p class="pending">Loading sheet export support…</p>{/if}</Modal>
  <Modal open={dialog==='laposte'} title="La Poste sheets" onClose={()=>dialog=''}>{#if selectedRoute.id==='cloud-api'&&!cloudPrinter?.online}<p class="pending">Cloud La Poste printing requires the selected printer to be online. Queue only one current label while it is offline.</p>{/if}{#if sdk}<LaPostePanel {sdk} route={selectedRoute.id==='cloud-api'&&!cloudPrinter?.online?undefined:selectedRoute} printRequest={printers.find(item=>item.id===printerId)?{printer:printers.find(item=>item.id===printerId)!,copies:1}:undefined}/>{:else}<p class="pending">Select a printer model to load the printer SDK first.</p>{/if}</Modal>
</div>
<style>
  .app{height:100dvh;min-width:0;overflow:hidden;display:grid;grid-template-rows:minmax(0,1fr) auto}
  .app :global(.mb-lockup){white-space:nowrap}
  .file{display:flex;gap:.5rem;align-items:center;width:100%;padding:.3rem .45rem;border-radius:var(--mb-radius-sm);cursor:pointer}
  .file:hover{background:var(--mb-surface-2)}
  .file input[type=file]{position:absolute;opacity:0;width:1px}
  .token{width:8rem}
  .primary{background:var(--mb-accent);color:var(--mb-text-on-accent);border:1px solid var(--mb-accent);border-radius:var(--mb-radius-sm);padding:.28rem .55rem;white-space:nowrap;cursor:pointer}
  .primary:hover:not(:disabled){background:var(--mb-accent-hover);border-color:var(--mb-accent-hover)}
  .primary:disabled{opacity:.45;cursor:default}
  .media-chip{padding:.22rem .45rem;border:var(--mb-border);border-radius:var(--mb-radius-sm);color:var(--mb-text-muted);font-size:.72rem;white-space:nowrap}
  .pending{margin:0;padding:.9rem;color:var(--mb-text-muted);font-size:.8125rem}
  .cloud-connect{display:flex;flex-direction:column;gap:.6rem;padding:.8rem}.cloud-connect label{display:flex;flex-direction:column;gap:.2rem;font-size:.75rem}.cloud-connect p{font-size:.75rem;color:var(--mb-text-muted)}
  footer{padding:.35rem 1rem;background:var(--mb-bg);color:var(--mb-text-muted);border-top:var(--mb-border);font-size:.75rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .offline{color:var(--mb-kiln-300)}
  @media(max-width:800px){.app :global(.appbar select){max-width:7.5rem}}
</style>
