// SPDX-License-Identifier: AGPL-3.0-or-later
export interface EvaluationContext { record: Record<string, string>; locale?: string; now?: Date; currentDate?: string }
const LIMIT=1_000_000;
export function evaluateTemplate(source:string,context:EvaluationContext):string{if(source.length>LIMIT)throw new Error('template limit exceeded');let output='';let rest=source;for(;;){const start=rest.indexOf('{{');if(start<0){output+=rest;break}output+=rest.slice(0,start);const after=rest.slice(start+2);const end=after.indexOf('}}');if(end<0)throw new Error('unclosed expression');const parts=after.slice(0,end).split('|').map(item=>item.trim());const field=parts[0];let value:string;if(field==='@date')value=context.currentDate??(context.now?context.now.toISOString().slice(0,10):'1970-01-01');else if(Object.hasOwn(context.record,field))value=context.record[field];else if(parts.slice(1).some(item=>item.startsWith('default:')||item.startsWith('if-empty:')))value='';else throw new Error(`unknown field: ${field}`);for(const transform of parts.slice(1))value=apply(transform,value,context);output+=value;if(output.length>LIMIT)throw new Error('template limit exceeded');rest=after.slice(end+2)}return output}
function apply(transform:string,value:string,context:EvaluationContext):string{if(transform==='upper')return value.toUpperCase();if(transform==='lower')return value.toLowerCase();if(transform==='trim')return value.trim();if(transform==='ascii')return[...value].filter(character=>character.charCodeAt(0)<128).join('');if(transform.startsWith('default:'))return value||unquote(transform.slice(8));if(transform.startsWith('prefix:'))return unquote(transform.slice(7))+value;if(transform.startsWith('suffix:'))return value+unquote(transform.slice(7));if(transform.startsWith('number:')){const raw=transform.slice(7);if(!/^\d+$/.test(raw))throw new Error(`invalid numeric/date value: ${transform}`);const formatted=formatDecimal(value,Math.min(9,Number(raw)));return(context.locale??'en').startsWith('fr')?formatted.replace('.',','):formatted}if(transform.startsWith('if-empty:')){const parts=transform.slice(9).split(/:(.*)/s);if(parts.length<2)throw new Error(`unknown transform: ${transform}`);return value===''?parts[0]:parts[1]}if(transform.startsWith('if-eq:')){const parts=transform.slice(6).split(':');if(parts.length<3)throw new Error(`unknown transform: ${transform}`);return value===parts[0]?parts[1]:parts.slice(2).join(':')}if(transform.startsWith('date:'))return formatDate(value,transform.slice(5));throw new Error(`unknown transform: ${transform}`)}
function formatDecimal(value:string,decimals:number){const normalized=value.trim().replace(',','.');const match=/^(-?)(\d+)(?:\.(\d*))?$/.exec(normalized);if(!match)throw new Error(`invalid numeric/date value: ${value}`);const negative=match[1]==='-';let whole=BigInt(match[2]);const fraction=match[3]??'';const kept=Array.from({length:decimals},(_,index)=>Number(fraction[index]??'0'));if(Number(fraction[decimals]??'0')>=5){let carry=true;for(let index=kept.length-1;index>=0&&carry;index--){if(kept[index]<9){kept[index]++;carry=false}else kept[index]=0}if(carry)whole++}const nonzero=whole!==0n||kept.some(digit=>digit!==0);return`${negative&&nonzero?'-':''}${whole}${decimals?`.${kept.join('')}`:''}`}
function formatDate(value:string,pattern:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error(`invalid numeric/date value: ${value}`);const[year,month,day]=value.split('-');const y=Number(year),m=Number(month),d=Number(day),leap=y%4===0&&(y%100!==0||y%400===0);const days=[0,31,leap?29:28,31,30,31,30,31,31,30,31,30,31];if(m<1||m>12||d<1||d>days[m])throw new Error(`invalid numeric/date value: ${value}`);return pattern.replace(/%./g,token=>token==='%Y'?year:token==='%m'?month:token==='%d'?day:token==='%%'?'%':(()=>{throw new Error(`unknown transform: ${pattern}`)})())}
const unquote=(value:string)=>value.startsWith('"')&&value.endsWith('"')?value.slice(1,-1):value;
export function evaluateBatch(source:string,records:Record<string,string>[],context:Omit<EvaluationContext,'record'>={}){return records.map(record=>evaluateTemplate(source,{...context,record}))}
